name: REBYTE CLI RELEASE

on:
  push:
    tags:
      - v**

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.36.x # Run with latest stable Deno.
      - name: Build project
        run: ./build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            rebyte-linux-x64
            rebyte-macos-x64
            rebyte-macos-arm64